* Include SQLCOLMETA.INC
* ------------------------------------------------------------
* Descripcion: Definicione de estructura de metadatos
* Propietario: Salvador Rigau
* Autor:       Salvador Rigau
* Fecha:       01-06-2004
* Version:     1.1
* ------------------------------------------------------------
EQU s_TABLE_SCHEMA       TO  1
EQU s_OWNER              TO  2
EQU s_TABLE_NAME         TO  3
EQU s_COLUMN_NAME        TO  4
EQU s_DATA_TYPE          TO  5
EQU s_DATA_TYPE_NAME     TO  6
EQU s_NUMERIC_PRECISION  TO  7
EQU s_CHAR_MAX_LENGTH    TO  8
EQU s_NUMERIC_SCALE      TO  9
EQU s_NUMERIC_PREC_RADIX TO 10
EQU s_NULLABLE           TO 11
EQU s_REMARKS            TO 12
EQU s_COL_DEFAULT        TO 13
EQU s_IN_ASSOCIATION     TO 14
EQU s_AMC                TO 15
EQU s_ACOL_NO            TO 16
EQU s_MULTI_VALUE        TO 17
EQU s_DISPLAY_SIZE       TO 18
EQU s_AUTO_INCREMENT     TO 19
EQU s_CASE_SENSITIVE     TO 20
EQU s_COUNT              TO 21
EQU s_SEARCHABLE         TO 22
EQU s_LABEL              TO 23
EQU s_UNSIGNED           TO 24
EQU s_UPDATABLE          TO 25
EQU s_CONVERSION         TO 26
EQU s_FORMAT             TO 27

